### ISSUE TITLE
Does not stay in peep-dired mode when traversing directories

### ISSUE THREAD

**Issue by eethann** [asok/peep-dired#3]
First off, thanks so much for this. I was working on a code review project over the weekend and searching for something like this (inspired by Sublime Text's preview), and here it is!

I'm interested in helping, but will log a few issues.

First off, it feels awkward to lose peep mode when I descend into a directory with Dired. Can dired automatically open in peep mode when the prior directory was in peep mode? Is there another solution to this that is better?

**Comment by itsjeyd** [comment]
> Can dired automatically open in peep mode when the prior directory was in peep mode?

:+1: I prefer this behavior as well.

> I just felt that it might be counter intuitive, but maybe in fact it is not.

You're right, opinions about what's intuitive and what's usually differ. It might be a good idea to introduce a configuration option (sth like `peep-dired-stay-active-on-descent`) that controls the default behavior.

---

Other than that, thanks for creating `peep-dired`! :)

**Comment by vsrepo** [comment]
:+1 I would love this too, now I need to call `peep-dired` every time I change dir. It would be nice if it was on for any navigation, not just on descent, something like `peep-dired-stay-active-always`

**Comment by priyadarshan** [comment]
:+1:  I would love this too, now I need to call `peep-dired` every time I change dir. It would be nice if it was on for any navigation, not just on descent, something like `peep-dired-stay-active-always`

**Comment by priyadarshan** [comment]
This works very nicely now. It seems to stop working if `(setq peep-dired-cleanup-eagerly t)` is called.
